export {default as moon} from '../assets/destination/image-moon.png'
export {default as mars} from '../assets/destination/image-mars.png'
export {default as europa} from '../assets/destination/image-europa.png'
export { default as titan } from '../assets/destination/image-titan.png'
export { default as douglas } from '../assets/crew/image-douglas-hurley.png'
export { default as mark } from '../assets/crew/image-mark-shuttleworth.png'
export { default as victor } from '../assets/crew/image-victor-glover.png'
export { default as anousheh } from '../assets/crew/image-anousheh-ansari.png'